Update android to 12.1.0
defold/extension-facebook pull request #44
Opened 2021-11-22 11:06 UTC by SalavatR

2021-11-22 12:51 UTC, JCash commented
Thanks for you contribution.
Please make some comments in your PR about the changes you've made and the rationale behind them.

Also, we cannot just update the Android version without the matching iOS implementation.
So, please add changes there as well.

Finally, updating from version 9 to 12 is a large leap. What are the anticipated ramifications for the users?
Is there a new minimum os version or similar constraints?

2021-11-22 12:53 UTC, JCash requested changes

2021-11-22 12:53 UTC, JCash commented on facebook/src/facebook_android.cpp
> -        g_Facebook.m_Deactivate = env->GetMethodID(fb_app_class, "deactivate", "()V");
Why is this functions removed?

2021-11-22 12:53 UTC, JCash commented on facebook/src/java/com/defold/facebook/FacebookJNI.java
> +                new AppLinkData.CompletionHandler() {
It is hard to see the changes made since the indentation changed for this code block, and there are no comments on the code.

2021-11-24 09:33 UTC, ekharkunov-ms commented
It's need to add in ext.manifest in field aaptExtraPackage following:
`'androidx.lifecycle.runtime', 'androidx.lifecycle.viewmodel', 'androidx.savedstate', 'androidx.fragment', 'androidx.core'`
We updated facebook internally and we've got crashes on open login activity. Crashes connected to ClassNoDefFound (not found R classes from androidx packages).

2023-07-18 09:03 UTC, britzl commented
The extension has already been updated to 14.1.0. Closing.

2023-07-18 09:03 UTC, closed without merging